/********************************************************************
* alibavaCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error alibavaCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablealibavaCint();
extern void G__cpp_setup_inheritancealibavaCint();
extern void G__cpp_setup_typetablealibavaCint();
extern void G__cpp_setup_memvaralibavaCint();
extern void G__cpp_setup_globalalibavaCint();
extern void G__cpp_setup_memfuncalibavaCint();
extern void G__cpp_setup_funcalibavaCint();
extern void G__set_cpp_environmentalibavaCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "analysis.h"
#include "DataFileRoot.h"
#include "AsciiRoot.h"
#include "HDFRoot.h"
#include "Tracer.h"
#include "utils.h"
#include "Hit.h"
#include "Data.h"
#include "ChanList.h"
#include "sin_preguntas.h"
#include "crrc.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__alibavaCintLN_string;
extern G__linked_taginfo G__alibavaCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__alibavaCintLN_TF1;
extern G__linked_taginfo G__alibavaCintLN_TH1;
extern G__linked_taginfo G__alibavaCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__alibavaCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__alibavaCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__alibavaCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__alibavaCintLN_TProfile;
extern G__linked_taginfo G__alibavaCintLN_TH2;
extern G__linked_taginfo G__alibavaCintLN_TGraph;
extern G__linked_taginfo G__alibavaCintLN_EventBlock;
extern G__linked_taginfo G__alibavaCintLN_EventData;
extern G__linked_taginfo G__alibavaCintLN_EventDataBlock;
extern G__linked_taginfo G__alibavaCintLN_Hit;
extern G__linked_taginfo G__alibavaCintLN_vectorlEHitcOallocatorlEHitgRsPgR;
extern G__linked_taginfo G__alibavaCintLN_vectorlEHitcOallocatorlEHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlEHitcOallocatorlEHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_ChanList;
extern G__linked_taginfo G__alibavaCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_DataFileRoot;
extern G__linked_taginfo G__alibavaCintLN_DataFileRootcLcLScanType;
extern G__linked_taginfo G__alibavaCintLN_DataFileRootcLcLRunType;
extern G__linked_taginfo G__alibavaCintLN_vectorlEChanListcOallocatorlEChanListgRsPgR;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlEChanListcOallocatorlEChanListgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_AsciiRootPriv;
extern G__linked_taginfo G__alibavaCintLN_AsciiRoot;
extern G__linked_taginfo G__alibavaCintLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_AsciiRootcLcLBlockType;
extern G__linked_taginfo G__alibavaCintLN_HDFRootPrivate;
extern G__linked_taginfo G__alibavaCintLN_HDFRoot;
extern G__linked_taginfo G__alibavaCintLN_Tracer;
extern G__linked_taginfo G__alibavaCintLN_dequelEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__alibavaCintLN_TProfile2D;
extern G__linked_taginfo G__alibavaCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__alibavaCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__alibavaCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__alibavaCintLN_TCanvas;
extern G__linked_taginfo G__alibavaCintLN_TGraphErrors;

/* STUB derived class for protected member access */
